bug fix
asm89/stack-cors pull request #92
Opened 2021-03-11 21:03 UTC by selcukcukur

Interestingly, the container pretends it does not exist when the string symbol is not inserted. For this reason, the string characters = [] are included by default.

2021-03-11 21:22 UTC, GrahamCampbell requested changes

2021-03-11 21:22 UTC, GrahamCampbell commented on src/CorsService.php
> +    private function normalizeOptions(array $options = []): array
👎

2021-03-11 21:22 UTC, GrahamCampbell commented
What does this fix?

2021-03-12 05:54 UTC, selcukcukur commented
> What does this fix?

I checked the last changes I made. The container sees the "$options" variable as blank and the application does not start. Maybe it's just a problem I have, I'm not sure. need to be tested.

2021-03-12 06:04 UTC, selcukcukur commented
"Unresolvable dependency resolving [Parameter #0 [ <required> array $options]]" This way the parameter could not be resolved. It fixes this.

2021-03-12 08:41 UTC, barryvdh commented
You need to pass options, otherwise it doesn't work (no allowed headers). What framework are you using?

2021-03-12 10:27 UTC, selcukcukur commented
> You need to pass options, otherwise it doesn't work (no allowed headers). What framework are you using?

V8.32.1

2021-03-12 10:47 UTC, barryvdh commented
Are you using https://github.com/fruitcake/laravel-cors ?

2021-03-12 12:07 UTC, selcukcukur commented
> Are you using https://github.com/fruitcake/laravel-cors ?
Yes I did a standard setup and tried it at that time. I encountered the error I wrote above.

2021-03-12 12:11 UTC, barryvdh commented
I think you're probably missing something, or using the wrong Cors middleware in that case.

2021-03-12 21:19 UTC, selcukcukur commented
> I think you're probably missing something, or using the wrong Cors middleware in that case.

I'm not sure I'll do a test and check the situation again.

2021-03-15 08:57 UTC, closed without merging